# Name
name: Update Data


# Define schedule
on: 
  schedule:
    - cron: '0 0 * * 6,0' # run Runs at 00:00, only on Saturday and Sunday.

# Define jobs to be executed
jobs:
  build:
  runs-on: ubuntu-latest
  steps: 

  # Step 1: checkout repo content
  - name: checkout repo content
  # repository content to gitgub runner
  uses: actions/checkout@v2
  
  # Step 2: setup python
  - name: setup python
  uses: actions/setup-python@v4
  with:
  python-version: '3.9' #install python 3.9

  # Step 3: Install packages
  - name: install packages
  run:
  python -m pip install --upgrade pip
  pip install -r requirements.txt
  
  
  # Step 4: Run script
  -name: run script
  env: 
  # set env variables
  BLOB_STRING: ${{ secrets.BLOB_STRING }}
  CONN_STRING: ${{ secrets.CONN_STRING }}
  CONTAINER_NAME:  ${{ secrets.CONTAINER_NAME }}
  # run script
  run: python main.py
  

  
